mdapi/unpackaged/objects/Basecamp_Questionnaire_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Questionnaire Responses</relationshipLabel>
        <relationshipName>Questionnaire_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Version</label>
        <referenceTo>Basecamp_Version__c</referenceTo>
        <relationshipLabel>Questionnaire Responses</relationshipLabel>
        <relationshipName>Questionnaire_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/unpackaged/classes/Basecamp_LotteryWinner_LCC.cls
public class Basecamp_LotteryWinner_LCC {
    @AuraEnabled
    public static List<String> getLotteryParticipants(String recordId) {
        final List<String> lottery_handles = new List<String>();
        for (List<Basecamp_Questionnaire_Response__c> responses : [SELECT Account__r.PersonEmail FROM Basecamp_Questionnaire_Response__c where Version__c=: recordId]) {
            for (Basecamp_Questionnaire_Response__c response : responses) {
                String email = response.Account__r.PersonEmail;
                if (String.isEmpty(email)) continue;
                Integer idx = email.indexOf('@');
                lottery_handles.Add(email.substring(0, idx));
            }
        }
        System.debug('Found <' + lottery_handles.size() + '> responses');
        return lottery_handles;
    }
}